# Generated by Django 4.1.2 on 2022-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='имя пользователя', max_length=20)),
                ('password', models.TextField(help_text='пароль')),
            ],
        ),
    ]
