# Generated by Django 4.1.2 on 2022-11-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='имя')),
                ('weapon', models.TextField(help_text='оружие')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='описание оружия')),
            ],
        ),
    ]
