# Generated by Django 4.1.3 on 2022-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0002_character_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ename',
            field=models.TextField(default='Mona', help_text='имя для поисковой строки'),
        ),
    ]
