# Generated by Django 4.1.2 on 2022-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0002_character_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.TextField(default='Гидро', help_text='стихия'),
        ),
        migrations.AddField(
            model_name='character',
            name='ename',
            field=models.TextField(default='Mona', help_text='имя для ссылок'),
        ),
        migrations.AddField(
            model_name='character',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/albedo/character/Diluc'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='ename',
            field=models.TextField(default='SkySword', help_text='имя для ссылок'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/albedo/weapon/SkySword'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.TextField(default='Небесный меч', help_text='название оружия'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='typeof',
            field=models.TextField(default='Меч', help_text='название оружия'),
        ),
    ]
