# Generated by Django 4.1.3 on 2022-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0003_character_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/albedo/character/Mona'),
        ),
    ]
