# Generated by Django 4.1.2 on 2022-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0003_character_element_character_ename_character_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='ename',
            field=models.TextField(default='TheWidsith', help_text='имя для ссылок'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.TextField(default='Песнь Странника', help_text='название оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='typeof',
            field=models.TextField(default='Катализатор', help_text='название оружия'),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulidID', models.TextField(help_text='ID')),
                ('ename', models.TextField(default='Mona', help_text='имя для ссылок')),
                ('weapon', models.TextField(default='TheWidsith', help_text='оружие')),
                ('typeof', models.TextField(default='DPS', help_text='тип билда')),
                ('artiset1', models.TextField(default='Эмблема рассечённой судьбы', help_text='сет артефактов1')),
                ('artiset2', models.TextField(default='Эмблема рассечённой судьбы', help_text='сет артефактов2')),
                ('flower', models.TextField(default='HP', help_text='цветок')),
                ('feather', models.TextField(default='ATK', help_text='перо')),
                ('sands', models.TextField(default='ATK%', help_text='часы')),
                ('goblet', models.TextField(default='Elemental Damage Bonus%', help_text='кубан')),
                ('circlet', models.TextField(default='Crit Rate%', help_text='корона')),
                ('friends', models.ManyToManyField(to='albedo.character')),
            ],
        ),
    ]
