# Generated by Django 4.1.3 on 2022-11-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0004_character_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.TextField(default='Волчья погибель', help_text='название оружия'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='typeof',
            field=models.TextField(default='меч', help_text='название оружия'),
        ),
        migrations.AlterField(
            model_name='character',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/albedo/character/Diluc'),
        ),
    ]
