# Generated by Django 4.1.2 on 2022-12-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0004_alter_weapon_ename_alter_weapon_name_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='build',
            name='friend1',
            field=models.TextField(default='Дилюк', help_text='союзник 1'),
        ),
        migrations.AddField(
            model_name='build',
            name='friend2',
            field=models.TextField(default='Джин', help_text='союзник 2'),
        ),
        migrations.AddField(
            model_name='build',
            name='friend3',
            field=models.TextField(default='Ке Цин', help_text='союзник 3'),
        ),
    ]
