# Generated by Django 4.1.3 on 2022-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0005_weapon_name_weapon_typeof_alter_character_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='ename',
            field=models.TextField(default='Skysword', help_text='имя для ссылок'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/albedo/weapon/Skysword'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ename',
            field=models.TextField(default='Mona', help_text='имя для ссылок'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.TextField(default='Небесный меч', help_text='название оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='typeof',
            field=models.TextField(default='Меч', help_text='название оружия'),
        ),
    ]
