# Generated by Django 4.1.2 on 2022-12-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0005_remove_build_friends_build_friend1_build_friend2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='bulidID',
        ),
    ]
