# Generated by Django 4.1.3 on 2022-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0006_weapon_ename_weapon_link_alter_character_ename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.TextField(default='Гидро', help_text='стихия'),
        ),
    ]
