# Generated by Django 4.1.3 on 2022-12-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0004_alter_weapon_ename_alter_weapon_name_and_more'),
        ('albedo', '0007_character_element'),
    ]

    operations = [
    ]
