# Generated by Django 4.1.3 on 2022-12-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0008_merge_20221209_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='friends',
        ),
        migrations.AddField(
            model_name='build',
            name='author',
            field=models.CharField(default='Кли', help_text='автор', max_length=20),
        ),
        migrations.AddField(
            model_name='build',
            name='friend1',
            field=models.TextField(default='Дилюк', help_text='союзник 1'),
        ),
        migrations.AddField(
            model_name='build',
            name='friend2',
            field=models.TextField(default='Джин', help_text='союзник 2'),
        ),
        migrations.AddField(
            model_name='build',
            name='friend3',
            field=models.TextField(default='Ке Цин', help_text='союзник 3'),
        ),
    ]
