# Generated by Django 4.1.3 on 2022-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0009_remove_build_friends_build_author_build_friend1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='region',
            field=models.TextField(default='Мондштадт', help_text='регион'),
        ),
    ]
