# Generated by Django 4.1.3 on 2023-01-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0006_remove_build_bulidid'),
        ('albedo', '0010_character_region'),
    ]

    operations = [
    ]
