# Generated by Django 4.1.3 on 2023-01-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0011_merge_0006_remove_build_bulidid_0010_character_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='author',
        ),
        migrations.RemoveField(
            model_name='character',
            name='region',
        ),
        migrations.AlterField(
            model_name='character',
            name='link',
            field=models.TextField(default='http://127.0.0.1:8000/albedo/character/Mona'),
        ),
    ]
