# Generated by Django 4.1.3 on 2023-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0012_remove_build_author_remove_character_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='ename',
        ),
        migrations.AddField(
            model_name='build',
            name='author',
            field=models.TextField(default='leonchik', help_text='автор'),
        ),
        migrations.AddField(
            model_name='build',
            name='bname',
            field=models.TextField(default='название', help_text='название билда'),
        ),
        migrations.AddField(
            model_name='build',
            name='cname',
            field=models.TextField(default='Мона', help_text='имя персонажа'),
        ),
    ]
