# Generated by Django 4.1.3 on 2023-01-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0013_remove_build_ename_build_author_build_bname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='typeof',
        ),
    ]
