# Generated by Django 4.1.3 on 2023-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0014_remove_build_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Эмблема рассечённой судьбы', help_text='имя')),
            ],
        ),
    ]
