# Generated by Django 4.1.3 on 2023-01-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0015_arts'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.TextField(default=''),
        ),
    ]
