# Generated by Django 4.1.3 on 2023-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0016_character_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.TextField(default='p'),
        ),
    ]
