# Generated by Django 4.1.3 on 2023-01-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0017_alter_character_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='link',
        ),
    ]
