# Generated by Django 4.1.3 on 2023-01-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0018_remove_character_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='link',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='typeof',
            field=models.TextField(default='Катализатор', help_text='тип оружия'),
        ),
    ]
