# Generated by Django 4.1.3 on 2023-01-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0020_build_iid_alter_character_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='picture',
            field=models.TextField(default='https://paimon.moe/images/characters/mona.png'),
        ),
    ]
