# Generated by Django 4.1.3 on 2023-01-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0021_build_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='picture',
            field=models.TextField(default='https://paimon.moe/images/weapons/the_widsith.png'),
        ),
    ]
