# Generated by Django 4.1.3 on 2023-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0022_weapon_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bigpicture',
            field=models.TextField(default='https://paimon.moe/images/characters/full/mona.png'),
        ),
    ]
