# Generated by Django 4.1.3 on 2023-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0023_character_bigpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='elepic',
            field=models.TextField(default='https://paimon.moe/images/elements/gydro.png'),
        ),
        migrations.AddField(
            model_name='character',
            name='raripic',
            field=models.TextField(default='https://static.wikia.nocookie.net/genshin-impact/images/6/69/%D0%98%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0_5_%D0%97%D0%B2%D1%91%D0%B7%D0%B4.png/revision/latest/scale-to-width-down/79?cb=20210226153349&path-prefix=ru'),
        ),
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='character',
            name='region',
            field=models.TextField(default='Мондштадт'),
        ),
    ]
