# Generated by Django 4.1.3 on 2023-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0024_character_elepic_character_raripic_character_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='circlet',
            field=models.TextField(default='https://static.wikia.nocookie.net/genshin-impact/images/e/e9/%D0%90%D1%80%D1%82%D0%B5%D1%84%D0%B0%D0%BA%D1%82_%D0%A2%D0%BB%D0%B5%D1%8E%D1%89%D0%B0%D1%8F_%D0%B2%D0%B5%D0%B4%D1%8C%D0%BC%D0%B8%D0%BD%D0%B0_%D1%88%D0%BB%D1%8F%D0%BF%D0%B0.png/revision/latest?cb=20210114105231&path-prefix=ru'),
        ),
        migrations.AddField(
            model_name='arts',
            name='feather',
            field=models.TextField(default='https://static.wikia.nocookie.net/genshin-impact/images/7/75/%D0%90%D1%80%D1%82%D0%B5%D1%84%D0%B0%D0%BA%D1%82_%D0%9F%D1%8B%D0%BB%D0%B0%D1%8E%D1%89%D0%B5%D0%B5_%D0%B2%D0%B5%D0%B4%D1%8C%D0%BC%D0%B8%D0%BD%D0%BE_%D0%BF%D0%B5%D1%80%D0%BE.png/revision/latest?cb=20210114105200&path-prefix=ru'),
        ),
        migrations.AddField(
            model_name='arts',
            name='flower',
            field=models.TextField(default='https://static.wikia.nocookie.net/genshin-impact/images/d/df/%D0%90%D1%80%D1%82%D0%B5%D1%84%D0%B0%D0%BA%D1%82_%D0%92%D0%B5%D0%B4%D1%8C%D0%BC%D0%B8%D0%BD_%D0%BE%D0%B3%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%86%D0%B2%D0%B5%D1%82%D0%BE%D0%BA.png/revision/latest?cb=20210114105051&path-prefix=ru'),
        ),
        migrations.AddField(
            model_name='arts',
            name='goblet',
            field=models.TextField(default='https://static.wikia.nocookie.net/genshin-impact/images/7/75/%D0%90%D1%80%D1%82%D0%B5%D1%84%D0%B0%D0%BA%D1%82_%D0%9F%D1%8B%D0%BB%D0%B0%D1%8E%D1%89%D0%B5%D0%B5_%D0%B2%D0%B5%D0%B4%D1%8C%D0%BC%D0%B8%D0%BD%D0%BE_%D0%BF%D0%B5%D1%80%D0%BE.png/revision/latest?cb=20210114105200&path-prefix=ru'),
        ),
        migrations.AddField(
            model_name='arts',
            name='sands',
            field=models.TextField(default='https://static.wikia.nocookie.net/genshin-impact/images/b/b3/%D0%90%D1%80%D1%82%D0%B5%D1%84%D0%B0%D0%BA%D1%82_%D0%92%D0%B5%D0%B4%D1%8C%D0%BC%D0%B8%D0%BD_%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B9_%D1%87%D0%B0%D1%81.png/revision/latest?cb=20210114105034&path-prefix=ru'),
        ),
    ]
