# Generated by Django 4.1.3 on 2023-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0026_alter_arts_circlet_alter_arts_feather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arts',
            name='circlet',
        ),
        migrations.RemoveField(
            model_name='arts',
            name='feather',
        ),
        migrations.RemoveField(
            model_name='arts',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='arts',
            name='goblet',
        ),
        migrations.RemoveField(
            model_name='arts',
            name='sands',
        ),
    ]
