# Generated by Django 4.1.3 on 2023-02-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0027_remove_arts_circlet_remove_arts_feather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='circlet',
            field=models.TextField(default='https://paimon.moe/images/artifacts/crimson_witch_of_flames_circlet.png'),
        ),
        migrations.AddField(
            model_name='arts',
            name='feather',
            field=models.TextField(default='https://paimon.moe/images/artifacts/crimson_witch_of_flames_feather.png'),
        ),
        migrations.AddField(
            model_name='arts',
            name='flower',
            field=models.TextField(default='https://paimon.moe/images/artifacts/crimson_witch_of_flames_flower.png'),
        ),
        migrations.AddField(
            model_name='arts',
            name='goblet',
            field=models.TextField(default='https://paimon.moe/images/artifacts/crimson_witch_of_flames_goblet.png'),
        ),
        migrations.AddField(
            model_name='arts',
            name='sands',
            field=models.TextField(default='https://paimon.moe/images/artifacts/crimson_witch_of_flames_sands.png'),
        ),
    ]
