# Generated by Django 4.1.3 on 2023-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albedo', '0028_arts_circlet_arts_feather_arts_flower_arts_goblet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
